# Generated by Django 5.0.6 on 2025-06-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20231224_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
